<?php
/**
 * Xcomic - Comic Management Script
 * (http://xcomic.sourceforge.net)
 *
 * $Id$
 */

if (!defined('IN_XCOMIC')) {
	die("Hacking attempt");
}

//Make sure database connection exists
$status = @include_once $xcomicRootPath.'includes/config.temp.php';
if($status === false)
{
	message("
     <p>
     Xcomic was not able to create a new user since the database connectivity
	information generated in step 01 is no longer available. This occured 
	because the temporary file generated by Xcomic that stored the database
	connectivity information was deleted or no longer accessible. Please make
	sure that the file $xcomicRootPath"."includes/config.temp.php still exists.
	If not, please <a href='$xcomicRootPath"."admin/install/index.php'>restart 
	the installation of Xcomic</a>.
     </p>
     <p>
     If you still need help you can always visit the 
     <a href='http://xcomic.mikexstudios.com/forum'>Xcomic Support Forums</a>.
     </p>
     ", 
	'config.temp.php missing!');
     exit;
}
//Create database object
$dsn = array(
     'phptype'  => $dbms,
     'username' => $dbUser,
     'password' => $dbPasswd,
     'hostspec' => $dbHost,
     'database' => $dbName,
);

include_once $xcomicRootPath.'admin/install/includes/checkandcreatedbconnection.php';

$id = $db->nextId($table_prefix.'users');
$sql = '
     INSERT INTO '.$table_prefix.'users 
     VALUES (
          '.$id.', 
          '.$db->quoteSmart($inNewUser).', 
          '.$db->quoteSmart(md5($inNewPass)).', 
          '.$db->quoteSmart($inNewEmail).')';
$result = $db->query($sql);
if (PEAR::isError($result))
{
     //User creation failed!
     header('Location: '.$xcomicRootPath.'admin/install/error/createnewuserfailed.php');
     exit;
}

?>
